spring.application.name=LearningPlatform

# --- CONEXIÓN ORACLE CLOUD ---
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 1. AQUÍ PONES LA RUTA (Después del TNS_ADMIN=)
# Usa barras normales / incluso en Windows.
spring.datasource.url=jdbc:oracle:thin:@p8xcms60lbl136b6_high?TNS_ADMIN=C:/Users/oyash/Desktop/Sexto_bimestre/Desarrollo_Backend_I/Semana_8/Wallet_Oracle

spring.datasource.username=ADMIN
spring.datasource.password=Miblanquito785

# --- SEGURIDAD Y WALLET ---
spring.jpa.properties.oracle.net.tns_admin=C:/Users/oyash/Desktop/Sexto_bimestre/Desarrollo_Backend_I/Semana_8/Wallet_Oracle

spring.jpa.properties.oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=C:/Users/oyash/Desktop/Sexto_bimestre/Desarrollo_Backend_I/Semana_8/Wallet_Oracle)))

# --- HIBERNATE Y JPA (CREACIÓN Y BORRADO) ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- INICIALIZACIÓN DE SQL ---
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# --- LOGGING ---
logging.level.org.hibernate=INFO
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

# --- HIKARI POOL ---
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=5